name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout weather check lambda repository
      uses: actions/checkout@v2
      with:
        repository: mateuszjanczak/weather-check-lambda
        path: app

    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Build with Maven
      run: cd app && mvn -B package --file pom.xml

    - name: Checkout terraform repository
      uses: actions/checkout@v2
      with:
        path: tf

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2

    - name: Copy package
      run: cp ./app/target/hello-dev.jar ./tf/

    - name: Terraform Init
      run: cd tf && terraform init

    - name: Terraform Format
      run: terraform fmt -check

    - name: LS
      run: tree .

    - name: Terraform Plan
      run: terraform plan

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve